# This workflow deploys to Docker Hub
name: docker-hub-deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to DockerHub
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - name: Build Jar file
        run: docker run --rm --env VERSION=$TAG --volume "$(pwd)":/home/gradle/project --workdir /home/gradle/project gradle gradle build copy
      - name: Authorize DockerHub
        run: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - name: Docker build tag
        run: docker build -t gscbinc/dashboard-core-web-service:$TAG
      - name: Docker push image
        run: docker push gscbinc/dashboard-core-web-service:$TAG
      - name: Create tag
        run: git tag -a $TAG -m "Creating tag $TAG"
      - name: Push new tag
        run: git push --tags
    env:
      TAG: 0.1.${{ github.run_number }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      GIT_COMMITTER_EMAIL: ${{ vars.GIT_COMMITTER_EMAIL }}
      GIT_COMMITTER_NAME: ${{ vars.GIT_COMMITTER_NAME }}